### ISSUE TITLE
Projects not working

### ISSUE THREAD

**Issue by hawkeye116477** [probot/workflow#21]
Welcome! I found another bug. Create card project function not working. I have error:
```
[39m[90m21:20:30.133Z[39m [32m INFO[39m http: [36mPOST / 200 - 3.26 ms[39m[90m (id=057b550a38c753f9)[39m

[90m21:20:31.269Z[39m [31mERROR[39m probot: [36mobjs.find is not a function[39m

[90m  TypeError: objs.find is not a function

      at Function.getID (/app/lib/plugins/projects.js:56:17)

      at Projects.getRepoProjects.then.response (/app/lib/plugins/projects.js:16:36)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by LeoColomb** [comment]
Which node version do you use?

**Comment by hawkeye116477** [comment]
@LeoColomb Node 8.11.1
