### ISSUE TITLE
Fails with no error

### ISSUE THREAD

**Issue by grrowl** [probot/workflow#3]
I've simplified some of the REQUEST/RESPONSE objects, but in essence it calls `on(...events)` in `configuration.js`, but sometime after that ends on ERROR:

```
> probot run ./index.js "--private-key" "thisismy.private-key.pem" "-p" "3000"

Listening on http://localhost:3000
09:35:09.190Z  INFO PRobot: creating token for installation 24945
REQUEST:  { 
  path: '/installations/24945/access_tokens',
  method: 'post', ...
}
REQUEST BODY: {}

STATUS: 201
HEADERS: {"server":"GitHub.com","x-github-request-id":"F67B:6828:708765:874274:591D6ACD"}
REQUEST:  { host: 'api.github.com',
  path: '/repos/grrowl/bot-test/contents/.probot.js',
  method: 'get',
  headers: {},
  ca: undefined }
STATUS: 200
HEADERS: {"server":"GitHub.com","x-github-request-id":"F67C:6828:708839:8743C9:591D6ACE"}
09:35:11.299Z ERROR PRobot:
```

Specifying `LOG_FORMAT=bunyan` prints the error as this:

```
{"name":"PRobot","hostname":"tombookpro.local","pid":2310,"level":50,"msg":"","time":"2017-05-18T09:41:32.362Z","v":0}
```

**Comment by grrowl** [comment]
Had to override the logger in `probot/lib/robot.js` with this `Robot.prototype.log.error = function (a) { console.error("ERROR:", a) }`

which yielded the true error:

```
ERROR: TypeError: on(...).filter(...).merge is not a function
    at evalmachine.<anonymous>:25:4
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at Object.runInContext (vm.js:87:6)
    at Sandbox.execute (/Users/tom/Documents/repos/probot-workflow/lib/sandbox.js:10:8)
    at Configuration.parse (/Users/tom/Documents/repos/probot-workflow/lib/configuration.js:54:26)
```

**Comment by grrowl** [comment]
which was an error in my `.probot.js` file

```
on('pull_request.labeled')
  // has a label to merge
  .filter(event => event.payload.label === 'enhancement')
  // merge PR
  .merge()
```

**Comment by grrowl** [comment]
plenty of examples in `examples.md` don't work (as to be expected based on the preamble), but the real issue is suppressing parse errors (like this one) in the `.probot.js`:

```
TypeError: on(...).filter.labeled is not a function
```

Might look at setting `displayErrors` in Sandbox (to node's `vm`) or switching to the more secure `vm2`
